package org.entities;
import javax.persistence.*;
// Generated Dec 30, 2020, 7:37:37 PM by Hibernate Tools 5.4.21.Final

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name  = "book")
public class Book implements java.io.Serializable {

	private Integer idBook;
	private String title;
	private String author;
	private double price;

	public Book() {
	}

	public Book(String title, String author, double price) {
		this.title = title;
		this.author = author;
		this.price = price;
	}
	@Id
	@Column(name = "idBook")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getIdBook() {
		return this.idBook;
	}

	public void setIdBook(Integer idBook) {
		this.idBook = idBook;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "Book [idBook=" + idBook + ", title=" + title + ", author=" + author + ", price=" + price + "]";
	}
	
}
