package org.huyha.entities;
// Generated Dec 30, 2020, 11:43:50 AM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private Integer idClass;
	private String className;
	private Set students = new HashSet(0);

	public Class() {
	}

	public Class(String className, Set students) {
		this.className = className;
		this.students = students;
	}

	public Integer getIdClass() {
		return this.idClass;
	}

	public void setIdClass(Integer idClass) {
		this.idClass = idClass;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
