package org.huyha.entities;
// Generated Dec 30, 2020, 11:43:50 AM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private Classes class_;
	private String name;
	private Date dateOfBirth;
	private Boolean sex;

	public Student() {
	}

	public Student(Classes class_, String name, Date dateOfBirth, Boolean sex) {
		this.class_ = class_;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

	public Classes getClass_() {
		return class_;
	}

	public void setClass(Classes class_) {
		this.class_ = class_;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@Override
	public String toString() {
		return "Student [id=" + id + ", class_=" + class_ + ", name=" + name + ", dateOfBirth=" + dateOfBirth + ", sex="
				+ sex + "]";
	}
	
}
