package org.entities;
// Generated Dec 31, 2020, 12:39:25 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer idClass;
	private Serializable className;
	private Set students = new HashSet(0);

	public Classes() {
	}

	public Classes(Serializable className, Set students) {
		this.className = className;
		this.students = students;
	}

	public Integer getIdClass() {
		return this.idClass;
	}

	public void setIdClass(Integer idClass) {
		this.idClass = idClass;
	}

	public Serializable getClassName() {
		return this.className;
	}

	public void setClassName(Serializable className) {
		this.className = className;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
