package org.entities;
// Generated Dec 31, 2020, 12:39:25 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "Student")
public class Student implements java.io.Serializable {
	@Id
	@Column(name = "ID" )
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	@ManyToOne
	@JoinColumn(name = "ID_Class")
	private Classes classes;
	
	private Serializable name;
	private Date dateOfBirth;
	private Boolean sex;

	public Student() {
	}

	public Student(Classes classes, Serializable name, Date dateOfBirth, Boolean sex) {
		this.classes = classes;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.sex = sex;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

}
